# Generated by Django 5.2.5 on 2026-06-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_authauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='keycloak_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
