# Generated by Django 5.2.5 on 2026-06-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_customer_keycloak_user_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authauditlog',
            new_name='Customer_au_user_id_b165d8_idx',
            old_name='Customer_au_user_id_d35151_idx',
        ),
        migrations.RenameIndex(
            model_name='authauditlog',
            new_name='Customer_au_action_de9961_idx',
            old_name='Customer_au_action_50d4d3_idx',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='Customer_ot_user_id_ef87b2_idx',
            old_name='Customer_ot_user_id_6a8af8_idx',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='Customer_ot_user_id_4720e6_idx',
            old_name='Customer_ot_user_id_64d4f2_idx',
        ),
    ]
