# Generated by Django 5.2.5 on 2026-05-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['business_name'], name='Seller_sell_busines_de973c_idx'), models.Index(fields=['business_email'], name='Seller_sell_busines_e5ba35_idx')],
            },
        ),
    ]
