# Generated by Django 5.2.5 on 2026-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_marketplace_seller_reviews_and_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/main/'),
        ),
    ]
